### ISSUE TITLE
b<Symbol> must be modified as well as __bank_<Symbol>

### ISSUE THREAD

**Issue by untoxa** [chrismaltby/gbspack#1]
`b<Symbol>` is emitted in pair to `<Symbol>` when Symbol is a function:
```
void foo() __banked {};
```
symbol `foo` has a pair `bfoo`. but you should not modify any symbol that begins with "b", only those that have a pair. then your tool will work for code as well as data.

**Comment by chrismaltby** [comment]
Interesting, so potentially all banked functions could be packed without needing to worry exactly where they are. I've added this in 3f6abbd38b65c5b44c0ec4b01ba3f59a3e91c8e5 and made a 1.1.0 release including this and the extension flag update at https://github.com/chrismaltby/gbspack/releases/tag/v1.1.0

**Comment by untoxa** [comment]
why potentially? they will definitely work! so, actually, you don't need -b switch, you may always begin with 1.
