### ISSUE TITLE
Output max bank number used

### ISSUE THREAD

**Issue by chrismaltby** [chrismaltby/gbspack#3]
Add `--print-max` flag to output the maximum bank number used, optionally rounding up to the nearest power of 2 so that this value can be passed to the GBDK linker to set the minimum required cartridge size `-Wl-yo$(CART_SIZE)`

**Comment by untoxa** [comment]
yes, it is nice, if tool returns a number that can be passed into the linker later.

**Comment by chrismaltby** [comment]
cool, I've added `--print-max` / `-p` for outputting the maximum bank used and `--print-cart` / `-c` for outputting the minimum cart size needed in 1.2.0 https://github.com/chrismaltby/gbspack/releases/tag/v1.2.0
